Updating the reset logic to PLL and debug ports for clk62m5, wrpc res…
NuQuantum/wr-cores pull request #10
Opened 2024-09-20 14:38 UTC by rromerson

…et, and system clock select

Added constants for the wb_crossbar address map. The crossar is not the primary one inside the WRPC core,  but the one directly connected to kasli soc peripherals (sci549 and more). At the primary crossbar within WPRC core, peripherals are connected from , so the same 0x00020000 has been assined to the Core wishone slave interface at the secondary (kasli) crossbar. Mask has been assigned as x000F_0000 (only 5th digit matters). Also updated the debug pins in the declaration of componenets xwrc_board_kasli and wrc_board_kasli.

Included an edge detecttion for signal reg2hw.SYSTEM_CLOCK_SELECT which is now used totdrive the reset going to the PLL within xwrc_platform_xilinx. Added external ports for debugging internal signals with respect to clock_62m5, clock_select, wrpc_reset_core. Logic for these signals was also added, including CDC and exporting the  via ODDR primitive.

Added external ports for debugging internal signals with respect to clock_62m5, clock_select, wrpc_reset_core.

2024-09-20 15:50 UTC, Jonah-Foley requested changes
A few nit pick comments, and some thoughts about whether the conversion to differential for debug signals should be performed here. If there is pressure to get this merged not all the nit-pick comments need to be addressed, but note them for the future.

2024-09-20 15:50 UTC, Jonah-Foley commented on board/kasli/wr_kasli_pkg.vhd
> +  -- Addresses in the range x"0000_0xxx" belong to the HDL modules connected to the primary crossar inside the core.
should this be `x"0000_xxxx"`?

2024-09-20 15:50 UTC, Jonah-Foley commented on board/kasli/wr_kasli_pkg.vhd
> +      d_clock_62m5_signal_p  : out std_logic := '0'
style: align the `:` of signals here. You can run your file through the [vsg](https://vhdl-style-guide.readthedocs.io/en/latest/usage.html) tool to auto correct this.

You'd run something like
```
vsg -f wr_kasli_pkg.vhd --fix
```
Edit: having looked at the other files I think it would be best to run `vsg` on those too. This would resolve most formatting issues.

2024-09-20 15:50 UTC, Jonah-Foley commented on board/kasli/wr_kasli_pkg.vhd
> +      d_clock_62m5_signal_p  : out std_logic := '0'
As above, style (alignment).

2024-09-20 15:50 UTC, Jonah-Foley commented on board/kasli/wrc_board_kasli.vhd
> +    d_clock_62m5_signal_p  : out std_logic := '0'
As above, stlye (alignment).

2024-09-20 15:50 UTC, Jonah-Foley commented on board/kasli/wrc_board_kasli.vhd
> +      d_clock_62m5_signal_p => d_clock_62m5_signal_p
style: align the `=>` of signals here. Again, the `vsg` tool will catch this.

2024-09-20 15:50 UTC, Jonah-Foley commented on board/kasli/xwrc_board_kasli.vhd
> +    d_clock_62m5_signal_p  : out std_logic := '0'
As above, stlye (alignment).

2024-09-20 15:50 UTC, Jonah-Foley commented on board/kasli/xwrc_board_kasli.vhd
> +  attribute async_reg of rst_wrpc_iii : signal is "true";
Depends on what @shareefj  thinks ... do we prefer to put these sort of attributes within the top level xdc file, as opposed to the source directly. If so we could create an `xwrc_board_kasli.xdc` and include it in the `core` file at this level.

2024-09-20 15:50 UTC, Jonah-Foley commented on board/kasli/xwrc_board_kasli.vhd
> +  signal clock_62m5_ODDR2BUF  : std_logic := '0';
For consistency, prefer `clk` as opposed to `clock` here.

2024-09-20 15:50 UTC, Jonah-Foley commented on board/kasli/xwrc_board_kasli.vhd
> +      areset_n_i             => reset_n_to_PLL, --'1', -- REVISIT: do we need to reset on clock switch? See UG472 p.91
Please remove the  REVISIT comment.

2024-09-20 15:50 UTC, Jonah-Foley commented on board/kasli/xwrc_board_kasli.vhd
> +  );
This applies to all primitive instantiations - please remove unnecessary comments. If there is a particular reason why a parameter is set one way leave the comment in, but for simple, well known primitives labelling each of the ios is unnecessary.

2024-09-20 15:50 UTC, Jonah-Foley commented on board/kasli/xwrc_board_kasli.vhd
> +  --   d_system_clock_select  <= cs_iii;
Can this comment be removed?

2024-09-20 15:50 UTC, Jonah-Foley commented on board/kasli/xwrc_board_kasli.vhd
> +  );
In general, i'm dont think we should be converting the debug signals to differential at this level of hierarchy for the following reasons:
- More typing when instantiating the module 
- The fact they are differential only becomes relevant when putting them out on the pins. Therefore we should perform the conversion as close to the pins as possible (in a logical sense, I understand this IOB wont change its physical position if its placed in a higher level module!) 
- If I was someone using the `wrc_board_kasli` module I'd probably wonder why the debug signals are differential. It may be that I want to route the debug signals to some single ended GPIO, which is not possible (?) given they are presented as a differential interface. That is, we only care to make the differential since _our_ use case is driving them over EEM to DIO cards, therefore that logic should exist within our custom top level that consumes this module. 

My suggestion is that we move all the OBUFDS' in this file to `kasli_soc_wrpc.sv`

2024-09-20 15:50 UTC, Jonah-Foley commented on board/kasli/xwrc_board_kasli.vhd
> +  cdc_gen_WRPCRstCore : IF TRUE GENERATE
style: the standard WR naming scheme seems to be that all instances of a component are prefixed with `cmp_`. We should stick to this since this code lives within the WR repo.

Also, we should stick to using snake case i.e. `cmp_cdc_gen_WRPC_Rst_Core` as that is used commonly throughout this repo. They are quite inconsistent with capitalisation, so no comment there.

2024-09-20 15:50 UTC, Jonah-Foley commented on board/kasli/xwrc_board_kasli.vhd
> +  signal cs_iii : std_logic := '0';
This more applies to verilog, but when you have multiple signals in a pipeline like this the lowRISC convention which we try to follow would be 

```
signal cs_i  : std_logic := '0';
signal cs_i2 : std_logic := '0';
signal cs_i3 : std_logic := '0';
```

Even better would be 
```
signal cs_q  : std_logic := '0';
signal cs_q2 : std_logic := '0';
signal cs_q3 : std_logic := '0';
```
since these signals are the output of a flop.

These rules are detailed here : https://github.com/lowRISC/style-guides/blob/master/VerilogCodingStyle.md#suffixes

For now, I dont think its necessary to change your implementation, but good to note for the future.

2024-09-20 17:20 UTC, rromerson commented
@Jonah-Foley I addressed all of your comments and created a new PR. As I explained you in person, I left CDC and clock forwarding within xwrpc_board_kasli.vhd and brought the conversion to differential signals to kasli_soc_wrpc.sv. There will be a new PR.

2024-09-23 09:52 UTC, shareefj commented
Re-opening

2024-09-23 10:42 UTC, rromerson commented on board/kasli/wr_kasli_pkg.vhd
> +  -- Addresses in the range x"0000_0xxx" belong to the HDL modules connected to the primary crossar inside the core.
Changed the comment - now including the real address range from CERN (as per file xwr_core.vhd).

2024-09-23 10:43 UTC, rromerson commented on board/kasli/wr_kasli_pkg.vhd
> +      d_clock_62m5_signal_p  : out std_logic := '0'
With the differential conversion brought to the top level, these ports no longer exist. The equivalent single ended ones are aligned accordingly.

2024-09-23 10:44 UTC, rromerson commented on board/kasli/wr_kasli_pkg.vhd
> +      d_clock_62m5_signal_p  : out std_logic := '0'
With the differential conversion brought to the top level, these ports no longer exist. The equivalent single ended ones are aligned accordingly.

2024-09-23 10:44 UTC, rromerson commented on board/kasli/wrc_board_kasli.vhd
> +    d_clock_62m5_signal_p  : out std_logic := '0'
With the differential conversion brought to the top level, these ports no longer exist. The equivalent single ended ones are aligned accordingly.

2024-09-23 10:46 UTC, rromerson commented on board/kasli/wrc_board_kasli.vhd
> +      d_clock_62m5_signal_p => d_clock_62m5_signal_p
The equivalent single ended ones are aligned accordingly.

2024-09-23 10:47 UTC, rromerson commented on board/kasli/xwrc_board_kasli.vhd
> +    d_clock_62m5_signal_p  : out std_logic := '0'
The equivalent single ended ones are aligned accordingly.

2024-09-23 10:51 UTC, rromerson commented on board/kasli/xwrc_board_kasli.vhd
> +  --   d_system_clock_select  <= cs_iii;
Removed.

2024-09-23 10:52 UTC, rromerson commented on board/kasli/xwrc_board_kasli.vhd
> +  );
Conversion now at top level file `kasli_soc_wrpc.sv`.

2024-09-23 10:52 UTC, rromerson commented on board/kasli/xwrc_board_kasli.vhd
> +  signal cs_iii : std_logic := '0';
Changed to recommended syntax.

2024-09-23 12:53 UTC, shareefj requested changes

2024-09-23 12:53 UTC, ghost commented on board/kasli/wr_kasli_pkg.vhd
> +  -- Address Map for the componenets connected to the WB_Crossbar outside the WRPC core - secondary crossbar.
Although this address map works, it's not a very efficient use of the address space.  Not that we care too much but we should probably optimise it.

You've got the WRPC at 0x0002_0000 until 0x0002_FFFF so I'd suggest using the address space at 0x0003_0000 until 0x0003_FFFF for our peripherals (each using 1KB or 0x400).  You don't need 128KB windows for a handful of registers.

2024-09-23 12:53 UTC, ghost commented on board/kasli/wr_kasli_pkg.vhd
> +      d_wrpc_reset_core     : out   std_logic := '0';
As with my comments in the multicore-qc PR, use a descriptive prefix such as `debug_` or `dbg_`.

2024-09-23 12:53 UTC, ghost commented on board/kasli/xwrc_board_kasli.vhd
> +  attribute async_reg of cs_q   : signal is "true";
Thought I'd seen a Jonah comment about this somewhere but please don't put any tool directives in source files.

2024-09-23 12:53 UTC, shareefj commented on board/kasli/xwrc_board_kasli.vhd
> +  signal clock_62m5_ODDR2BUF  : std_logic := '0';
And please don't mix capitals.  All signal names should be lower snake case.

2024-09-23 12:53 UTC, shareefj commented on board/kasli/xwrc_board_kasli.vhd
> +  DDR_clk62m5t : ODDR
I know the WR team use a load of different styles but can we stick to instance names that are all lower snake case and start with `u_` to match our SV style guide.

2024-09-23 15:28 UTC, rromerson commented on board/kasli/wr_kasli_pkg.vhd
> +  -- Address Map for the componenets connected to the WB_Crossbar outside the WRPC core - secondary crossbar.
Agreed. The thought was: let's go safe on the first try, but they've been changed now seeking optimization.

2024-09-23 15:28 UTC, rromerson commented on board/kasli/wr_kasli_pkg.vhd
> +      d_wrpc_reset_core     : out   std_logic := '0';
Done with dbg_.

2024-09-23 15:31 UTC, rromerson commented on board/kasli/xwrc_board_kasli.vhd
> +  attribute async_reg of cs_q   : signal is "true";
I replaced all of this logic with components from the package `gencores` from CERN. Bot CDC and edge detection are available, thus I used `gc_sync` for cdc and `gc_sync_ffs` for cdc and edge detection.

2024-09-23 15:31 UTC, rromerson commented on board/kasli/xwrc_board_kasli.vhd
> +  DDR_clk62m5t : ODDR
Both snake case and u_ adopted all over.

2024-09-23 15:52 UTC, Jonah-Foley requested changes
A few small naming items. Being annoying about it now so that we're on the right track from the start.

2024-09-23 15:52 UTC, Jonah-Foley commented on board/kasli/wr_kasli_pkg.vhd
> +                                     c_mask_kasli_periph;  -- secbar_master_in(5): Core wishone slave interface
If we are moving these to constants within `wr_kasli_pkg` then they should be removed as generics from the `wrc_board_kasli` module.

2024-09-23 15:52 UTC, Jonah-Foley commented on board/kasli/xwrc_board_kasli.vhd
> +  signal reset_n_to_pll     : std_logic := '0';
`_n` should be treated as a [suffix](https://github.com/lowRISC/style-guides/blob/master/VerilogCodingStyle.md#suffixes) - therefore prefer `reset_to_pll_n`. In addition, _which pll_? There are two: dmtd, and the sys pll. 

So perhaps
```suggestion
  signal reset_to_pll_sys_n     : std_logic := '0';
```

Also, seems as though `rst` is used more than `reset` - so maybe even:
```suggestion
  signal rst_pll_sys_n     : std_logic := '0';
```

2024-09-23 15:52 UTC, Jonah-Foley commented on board/kasli/xwrc_board_kasli.vhd
> +  signal cs_q2              : std_logic := '0';
`cs` - is that chip select? who knows - could be confusing. Verbosity should be preferred here

Something like 
 ```suggestion
  signal clk_sys_select_q2              : std_logic := '0';
```

2024-09-23 15:54 UTC, Jonah-Foley commented on board/kasli/wr_kasli_pkg.vhd
> +                                     c_mask_kasli_periph;  -- secbar_master_in(5): Core wishone slave interface
note: this comment was meant to go into the last review, my fault, but still applies.

2024-09-23 15:56 UTC, shareefj requested changes

2024-09-23 15:56 UTC, shareefj commented on board/kasli/wr_kasli_pkg.vhd
> +  -- Address Map for the componenets connected to the WB_Crossbar outside the WRPC core - secondary crossbar.
You don't need to compare all the bits of the address, just those that we care about.  So I think it could be `0x000F_FC00`

2024-09-23 15:56 UTC, shareefj commented on board/kasli/xwrc_board_kasli.vhd
> +      ppulse_o  => reset_n_to_pll
This isn't going to work.  You're going to hold the PLL in reset for all time.

What we want to do is detect a change in `SYSTEM_CLOCK_SELECT` and drive the reset to the PLL.  So I think you want to take both the `npulse` and `ppulse` outputs, logically or them together, and drive that into a shift register to provide a few cycles of reset.  

I can't think in VHDL so the Verilog would look like:

```
  assign clk_sel_change = npulse || ppulse;

  always@(posedge clk)
    pll_reset_sr_q[7:0] <= { pll_reset_sr_q[6:0], clk_sel_change };

  assign areset_n = ~|pll_reset_sr_q;
```

2024-09-23 15:56 UTC, shareefj commented on board/kasli/xwrc_board_kasli.vhd
> +      ppulse_o  => reset_n_to_pll
Try to maintain signal names across hierarchies.  So change `reset_n_to_pll` to `areset_n`.  If I were writing this code I'd also have broken out the reg records into nicely named signals too, so `reg2hw.SYSTEM_CLOCK_SELECT` would become `sys_clock_sel` or something similar and the synchronised version would have an `_s` suffix.

2024-09-23 16:13 UTC, rromerson commented on board/kasli/xwrc_board_kasli.vhd
> +      ppulse_o  => reset_n_to_pll
For the address map, I was wondering whether we would need to compare registers within those ranges (like registers in the Kasli register map slave interface). Or should we just leave this to the slaves themselves?

And for the edge detection, I might have got it wrong but the component only holds the `p_pulse` high for one cycle. From this point, yes we can easily add some VHDL logic to keep it set a couple of cycles more.

2024-09-23 16:16 UTC, rromerson commented on board/kasli/wr_kasli_pkg.vhd
> +                                     c_mask_kasli_periph;  -- secbar_master_in(5): Core wishone slave interface
We can keep the generic and connect the constant in the the wrapper? Or even the top level? I think it makes more sense..

2024-09-23 16:18 UTC, rromerson commented on board/kasli/xwrc_board_kasli.vhd
> +  signal reset_n_to_pll     : std_logic := '0';
I will rename it according to [https://github.com/NuQuantum/wr-cores/pull/10#discussion_r1771717072](url)

2024-09-23 16:20 UTC, shareefj commented on board/kasli/xwrc_board_kasli.vhd
> +      ppulse_o  => reset_n_to_pll
I don't understand the first question about the address map sorry.  All we're trying to do is direct the WB access to the correct slave so you only need to compare the bits of the address that hits each window.  But perhaps I'm not understanding the question and it's something completely different.

For the reset term, what is the polarity of the `areset_n`?

2024-09-23 16:21 UTC, Jonah-Foley commented on board/kasli/wr_kasli_pkg.vhd
> +                                     c_mask_kasli_periph;  -- secbar_master_in(5): Core wishone slave interface
That works :+1:

2024-09-23 16:38 UTC, rromerson commented on board/kasli/xwrc_board_kasli.vhd
> +      ppulse_o  => reset_n_to_pll
1) `0x000F_FC00` as mask will work. Case closed.

2) True. For `areset_n` I was considering the SYSTEM_CLOCK_SELECT with opposite behaviour (detecting pos_edge and not the other way around).

2024-09-24 11:31 UTC, Jonah-Foley commented on board/kasli/wr_kasli_pkg.vhd
> +                                     c_mask_kasli_periph;  -- secbar_master_in(5): Core wishone slave interface
@rromerson  While I was working on the sims I had a thought. These constants shouldnt be `std_logic_vector`s. They should be `t_wishbone_address_array`s since that's what the `xwrc_board_kasli` generic expects. Something like 

```
constant c_si549_master_addr : t_wishbone_address := x"0003_0C00";
  constant c_si549_helper_addr : t_wishbone_address := x"0003_0800";
  constant c_gp1_slave_addr    : t_wishbone_address := x"0003_0400";
  constant c_kasli_regs_addr   : t_wishbone_address := x"0003_0000";
  constant c_wr_core_addr      : t_wishbone_address := x"0002_0000";

  constant c_wb_crossbar_addr_kasli_periph : t_wishbone_address_array(c_num_wb_crossbar_slaves-1 downto 0) := (
    c_si549_master_addr,
    c_si549_helper_addr,
    c_gp1_slave_addr,
    c_kasli_regs_addr,
    c_wr_core_addr
  );

  constant c_mask_kasli_periph: t_wishbone_address := x"000F_FC00";

  constant c_wb_crossbar_mask_kasli_periph : t_wishbone_address_array(c_num_wb_crossbar_slaves-1 downto 0) := (
      c_mask_kasli_periph,
      c_mask_kasli_periph,
      c_mask_kasli_periph,
      c_mask_kasli_periph,
      c_mask_kasli_periph
  );
```

Though there may be a more concise way to write that if you know VHDL better!

2024-09-24 12:45 UTC, rromerson commented on board/kasli/wr_kasli_pkg.vhd
> +                                     c_mask_kasli_periph;  -- secbar_master_in(5): Core wishone slave interface
What about the conversion between *.sv and VHDL? Would it not be a problem?
If you have a look at [https://github.com/NuQuantum/wr-cores/blob/1a317bf09f1357335efd7a5f5e92e9f8fca57d6e/board/kasli/wrc_board_kasli.vhd#L362](url), I guess you wrote this to deal with the conversion.

2024-09-24 12:50 UTC, Jonah-Foley commented on board/kasli/wr_kasli_pkg.vhd
> +                                     c_mask_kasli_periph;  -- secbar_master_in(5): Core wishone slave interface
Discussed in person: not an issue since the reg map is specified entirely in VHDL world. There is no user configuration from SV.

2024-09-24 13:51 UTC, ghost commented on board/kasli/xwrc_board_kasli.vhd
> +  gen_reset_n_on_hold: for i in 1 to (pll_reset_sr_q'length - 1) generate
Not sure what the generate loop is doing?  Isn't the a VHDL equivalent of a reduction OR operator?  How do you do this in VHDL: `|vec[n:0]`

2024-09-24 14:23 UTC, rromerson commented on board/kasli/xwrc_board_kasli.vhd
> +  gen_reset_n_on_hold: for i in 1 to (pll_reset_sr_q'length - 1) generate
Yes there is. I included the function nor_reduction() from pkg std_logic_misc now.

2024-09-24 14:23 UTC, Jonah-Foley commented on board/kasli/xwrc_board_kasli.vhd
> +  gen_reset_n_on_hold: for i in 1 to (pll_reset_sr_q'length - 1) generate
Something like:

```
signal rst : std_logic;
process(pll_reset_sr_q)
  for i in  0 to pll_reset_sr_q'length - 1 loop
    rst = rst or pll_reset_sr_q(i);
  end loop
end process
```

with proper naming.

2024-09-24 14:26 UTC, Jonah-Foley approved these changes, later dismissed
LGTM

2024-09-24 14:29 UTC, rromerson commented on board/kasli/xwrc_board_kasli.vhd
> +  gen_reset_n_on_hold: for i in 1 to (pll_reset_sr_q'length - 1) generate
VHDL 2008 allows for reductions like:
anded <= and v;
ored <= or v;

VHDL '93 does not.

2024-09-24 14:49 UTC, shareefj approved these changes, later dismissed

2024-09-24 15:27 UTC, shareefj approved these changes

2024-09-24 15:28 UTC, merged