Nq 1576/add vunit tests
NuQuantum/wr-cores pull request #19
Opened 2024-10-04 15:39 UTC by RichardNorth-Nu

I have made a few changes to the wr code and added a couple of fixes to get the vunit tests working on Jonah's top level 
This contains the register map changes and some other minor things

2024-10-04 16:26 UTC, Jonah-Foley requested changes
I think there are some valid changes here but they should not all come in one PR. I would suggest you break this PR into one which just has the NQ changes (i.e. the register map) and then the changes which touch WR internals. That way if we ever need to deliver to them a patch with all our cumulative changes to the WR design they aren't entangled with our Kasli SoC additions. I also do not see how this relates to VUnit.

2024-10-04 16:26 UTC, Jonah-Foley commented on platform/xilinx/xwrc_platform_vivado.vhd
What is the reason for modifying this file? I understand this is the 'newer' platform file, but we dont use it in the design. If we wish to switch to this one we could do in the future but in its current state it is missing a few things. For example in `xwrc_platform_xilinx` we also export the sys PLL locked signal to the module I/O since its used in the reset procedure.

2024-10-04 16:26 UTC, Jonah-Foley commented on modules/wrc_core/wrc_periph.vhd
This file can be removed from the PR since this change has already been merged in #17

2024-10-04 16:26 UTC, Jonah-Foley commented on modules/wr_si549_interface/wr_si549_interface.vhd
The WR guys said that this file is still in development. If we start making changes to it now there will be merge conflct once they release it. That makes me question whether we want to modify it at all. Is it necessary for simulation to have this correction?

2024-10-04 16:26 UTC, Jonah-Foley commented on board/kasli/xwrc_board_kasli.vhd
> +  cmp_ibufgds_pllref : component IBUFDS --IBUFGDS
Please remove the IBUFGDS comment.

2024-10-07 08:47 UTC, shareefj requested changes

2024-10-07 08:47 UTC, shareefj commented on modules/wr_si549_interface/wr_si549_interface.vhd
Agree with Jonah:  https://ohwr.org/project/wr-cores/-/issues/98

Please open issues against the correct teams when you find this sort of thing and/or discuss with myself on how to best to solve it if it's a showstopper.  In this case it's just a warning that you can ignore as the error isn't used.

2024-10-07 08:47 UTC, shareefj commented on modules/wrc_core/wrc_periph.vhd
Can we also be very careful about white space changes.  We shouldn't be pushing white space changes to the repo as it just confuses things during diffs.

2024-10-07 08:47 UTC, shareefj commented on modules/wrc_core/wr_core.vhd
> -    g_dpram_initf               : string                         := "default";
Why are you changing a generic?

2024-10-07 08:47 UTC, shareefj commented on board/kasli/xwrc_board_kasli.vhd
> +  cmp_ibufgds_pllref : component IBUFDS --IBUFGDS
@Jonah-Foley Didn't we agree that the pllref input is unused in which case we should just remove this altogether and tie it off.

2024-10-07 08:47 UTC, shareefj commented on platform/xilinx/xwrc_platform_vivado.vhd
Agree, revert this.

2024-10-07 11:10 UTC, Jonah-Foley commented on board/kasli/xwrc_board_kasli.vhd
> +  cmp_ibufgds_pllref : component IBUFDS --IBUFGDS
Yes, it can be removed.

2024-10-07 15:21 UTC, rromerson commented on modules/wrc_core/wrc_periph.vhd
> +      g_ow_btp_overdrive    => 10
I think this is compatible with type string.

2024-10-08 08:45 UTC, RichardNorth-Nu commented on modules/wrc_core/wrc_periph.vhd
ok great, will remove it

2024-10-08 08:45 UTC, RichardNorth-Nu commented on platform/xilinx/xwrc_platform_vivado.vhd
I think you should be using this file. The _xilinx file contains ISE components. This one only contains Vivado components. We are using Vivado. If you feel strongly about using the ISE file then that's fine. But what is the engineering reason for using that. In Sims, I use the Vivado file, as you should be. ISE has not been supported for so long. Are you sure you want to vote that we do not support this file?

2024-10-08 08:51 UTC, RichardNorth-Nu commented on modules/wrc_core/wr_core.vhd
> -    g_dpram_initf               : string                         := "default";
I think they made a mistake with this generic. looking at the impure function f_load_mem_from_file() if this file name is "" or "none" then the function returns successfully with a all zeros. for nearly all the simulations that is what you want. "default" causes an exception. as does using the wrong file.

2024-10-08 09:00 UTC, shareefj commented on platform/xilinx/xwrc_platform_vivado.vhd
I don't understand what you mean by ISE vs Vivado components.  It's a VHDL file with primitives in it.  Nothing to do with the tool chain used.

We used this level of hierarchy because it wasn't clear at the time where the split was.  It makes no difference to us outside of the fact it's hard to read with all the generate blocks.

Also, when you say you're using the _vivado level of hierarchy in your sims, what do you mean?  You should be using our top level that is defined in the fusesoc core file.

2024-10-08 09:02 UTC, RichardNorth-Nu commented on modules/wr_si549_interface/wr_si549_interface.vhd
Think this was a show stopper in Modelsim for some reason, Although in both places the signal is driven to 0. It causes multiple drivers on that signal and I would suspect it is left over from when they first made the file. It is driven in the si549_if_wb.vhd module as it should be. I will try reverting that signal and see if there is actually an issue or whether the actual issue was elsewhere and I have fixed it.

2024-10-08 09:18 UTC, RichardNorth-Nu commented on platform/xilinx/xwrc_platform_vivado.vhd
I guess I am questioning that we should be using the xwrc_platform_vivado.vhd file
the unisim component PLL_BASE instantiated in the xwrc_platform_xilinx.vhd is only available if you compile the ISE Unisim packages. I found that modelsim cannot find this component declaration in the Vivado version of unisim(as xcelium should too). I think Vivado synthesis overlooks this. I was intending on bringing it into line with the work that Jonah had done on the xwrc_platform_xilinx.vhd file.

2024-10-08 09:28 UTC, shareefj commented on platform/xilinx/xwrc_platform_vivado.vhd
We've not seen any issues here and are simulating the design with Xcelium.  I think there's a wider question of how the CERN team are naming these files and why a tool name is included in what should be a technology specific target name, but that's beside the point.  When I questioned them on what we should be using they said we were find to continue with what we had chosen.

2024-10-08 09:32 UTC, Jonah-Foley commented on platform/xilinx/xwrc_platform_vivado.vhd
I've not looked deep into the xcelium logs, but I've compiled unisims via vivado and it seems to have PLL_BASE. 
```
(.venv) [jfoley@localhost renode]$ ls /opt/Xilinx/Vivado/2022.2/data/vhdl/src/unisims/retarget/ | grep PLL_BASE
PLL_BASE.vhd
```

2024-10-08 09:58 UTC, RichardNorth-Nu commented on platform/xilinx/xwrc_platform_vivado.vhd
ok I will remove this file from the PR and switch the sim to using xwrc_platform_xilinx.vhd

2024-10-10 09:13 UTC, shareefj commented on modules/wrc_core/wr_core.vhd
> -    g_dpram_initf               : string                         := "default";
OK, but given the generic is passed down through the hierarchy is it worth adding noise to the set of modified files?  I'd prefer if you removed the updates to this file and kept the changes to the Kasli-SoC specific ones.

2024-10-10 10:45 UTC, RichardNorth-Nu commented on modules/wrc_core/wr_core.vhd
> -    g_dpram_initf               : string                         := "default";
ok

2024-10-10 12:04 UTC, shareefj submitted a review, later dismissed

2024-10-11 11:07 UTC, Jonah-Foley submitted a review, later dismissed

2024-10-11 11:42 UTC, Jonah-Foley approved these changes

2024-10-11 11:43 UTC, merged